spring.application.name=supermarche

spring.datasource.url=jdbc:mysql://localhost:3306/supermarche
spring.datasource.username=root
spring.datasource.password=Oklm2022
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Configuration du port du serveur

server.port=8081

# Configuration de l'url par defaut

server.servlet.context-path=/api

# Clé de chiffrement du Jwt

Jwt.secret.key=qY0ysQf8yY10uRJtYoAP7dBUpkuu1Ej0hiYoaIowDUA=

# Les configurations Cloudinary

cloudinary.cloud_name=dycdqyspf
cloudinary.api_key=227486531617891
cloudinary.api_secret=zkJQUwlv7iR3BBga2V9kPPf_bOI
cloudinary.folder=supermarche/produits

# Taille maximale des uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB