spring.application.name=supermarche

spring.datasource.url=jdbc:mysql://localhost:3306/supermarche
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Configuration du port du serveur

server.port=8081

# Configuration de l'url par defaut

server.servlet.context-path=/api

# Clé de chiffrement du Jwt

Jwt.secret.key=1995253342b61444be3581a1a8e07d4f21317e33c6323f4b612d39c4951a03db
